CREATE EXTENSION IF NOT EXISTS "uuid-ossp";  -- Ensures the UUID extension is available

CREATE TABLE blogs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),  -- UUID primary key with default value generated by uuid-ossp
    title TEXT NOT NULL,  -- Title of the blog, limited to 255 characters
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,  -- Timestamp when the blog is created, defaults to current time
    content TEXT NOT NULL  -- Content of the blog (text field for longer content)
);
