CREATE EXTENSION IF NOT EXISTS "uuid-ossp";  -- Ensures the UUID extension is available

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),  -- UUID primary key with default value generated by uuid-ossp
    email TEXT NOT NULL CONSTRAINT uq_email UNIQUE,  -- email of the user
    password_hash TEXT NOT NULL,  -- password hash of the user
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,  -- Timestamp when the blog is created, defaults to current time
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
