CREATE EXTENSION IF NOT EXISTS "uuid-ossp";  -- Ensures the UUID extension is available

CREATE TABLE tokens (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),  -- UUID primary key with default value generated by uuid-ossp
    user_id UUID NOT NULL,
    refresh_token TEXT NOT NULL CONSTRAINT uq_token UNIQUE,  -- email of the user
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,  -- Timestamp when the blog is created, defaults to current time
    expires_at TIMESTAMPTZ,
    CONSTRAINT fk_user
        FOREIGN KEY(user_id)
        REFERENCES users(id)
);
