services:
  db:
    image: "postgres:17"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "example123"
      POSTGRES_USER: "i18u-service"
      POSTGRES_DB: "i18u"
  web:
    env_file: ".env"
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "5174:5174"
    volumes:
      - ".:/app"
    working_dir: "/app"
    command: "./gradlew run"
    environment:
      DB_DATABASE: "i18u"
      DB_HOST: "db"
      DB_PASS: "example123"
      DB_PORT: "5432"
      DB_USER: "i18u-service"
      KTOR_LOG_LEVEL: "TRACE"
      LOG_LEVEL: "TRACE"
      JWT_SECRET: "example_jwt_secret"
    depends_on:
      - "db"